[feat] 탈퇴 계정 유효기간 설정 및 계정 복구 추가
fcstudy-project/FastTime-backend pull request #112
Opened 2023-10-30 15:36 UTC by ghrltjdtprbs

## [feat] 탈퇴 계정 유효기간 설정 및 계정 복구 추가

- 회원 탈퇴 시 유효 기간을 1년으로 설정하고, 유효 기간이 지나면 db에서 삭제하는 기능 추가
- 탈퇴 유효 기간이 지나지 않은 계정(동일 이메일)으로 회원가입 시 기존 계정 복구 기능 추가
- join 리팩토링
- 계정 복구 Spring API Docs 추가

2023-10-31 07:10 UTC, JeongUijeong requested changes

2023-10-31 07:10 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/member/service/MemberService.java
> +                System.out.println("Member found and trying to recover.");
log로 남기는 게 어떨까요?

2023-10-31 07:10 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/member/service/MemberService.java
> +            }
global에서 enum으로 관리 중인 ErrorCode에 추가하고 커스텀 익셉션을 던져서 어드바이스에서 핸들링하는 것이 어떨까요? ㅎㅎ

2023-10-31 07:10 UTC, JeongUijeong commented on src/main/java/com/fasttime/domain/member/service/MemberService.java
> +            return ResponseDTO.res(HttpStatus.INTERNAL_SERVER_ERROR, "회원가입 실패 " + e.getMessage());
앞서 달았던 코멘트와 마찬가지로 익셉션 처리하는 것이 좋을 것 같아요~

2023-10-31 08:37 UTC, ghrltjdtprbs commented on src/main/java/com/fasttime/domain/member/service/MemberService.java
> +                System.out.println("Member found and trying to recover.");
print 문 삭제했습니다!

2023-11-01 09:11 UTC, Nine-JH approved these changes

2023-11-01 09:13 UTC, JeongUijeong approved these changes

2023-11-01 09:13 UTC, merged